swagger: "2.0"
info:
  title: Simple API
  version: 1.0.0

paths:
  /hello:
    get:
      summary: Say hello
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              message:
                type: string

