// Generated by Claude 3 Haiku
package main

import (
	"fmt"
	"sync"
)

func main() {
	var wg sync.WaitGroup

	messages := make(chan string)
	defer close(messages)

	for i := 0; i < 3; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			messages <- fmt.Sprintf("Hello from %d", i)
		}()
	}

	for i := 0; i < 3; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			msg := <-messages
			fmt.Println(msg)
		}()
	}

	wg.Wait()
}
