name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: |
          go test -race -coverprofile=coverage.out -covermode=atomic .Go/src/99-problems/p15-duplicate
          go tool cover -html=coverage.out -o coverage.html
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.html
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
